#!/usr/bin/env python3
"""
@file generate_crc32.py
@brief Generates the optimized CRC32 lookup table and C source file. python generate_crc32.py > ../src/crc32.c
@author Jose Miguel Guerra Ramirez
"""

POLYNOMIAL = 0xEDB88320

def calculate_crc32_table():
    table = []
    for i in range(256):
        crc = i
        for _ in range(8):
            if crc & 1:
                crc = (crc >> 1) ^ POLYNOMIAL
            else:
                crc >>= 1
        table.append(crc)
    return table

def generate_c_file(table):
    c_code = (
        "/**\n"
        " * @file crc32.c\n"
        " * @brief Implementation of the Lookup Table based CRC32 algorithm.\n"
        " * @note THIS FILE IS AUTO-GENERATED BY tools/generate_crc32.py\n"
        " * DO NOT EDIT MANUALLY.\n"
        " */\n\n"
        "#include \"../include/crc32.h\"\n\n"
        "static const uint32_t crc32_table[256] = {\n"
    )

    for i in range(0, 256, 8):
        chunk = table[i:i+8]
        row = "    " + ", ".join([f"0x{val:08X}" for val in chunk])
        if i + 8 < 256:
            row += ","
        c_code += row + "\n"
        
    c_code += (
        "};\n\n"
        "uint32_t crc32_calculate(const uint8_t *data, size_t length, uint32_t initial_crc) {\n"
        "    uint32_t crc = initial_crc;\n"
        "    for (size_t i = 0; i < length; i++) {\n"
        "        uint8_t table_index = (crc ^ data[i]) & 0xFF;\n"
        "        crc = (crc >> 8) ^ crc32_table[table_index];\n"
        "    }\n"
        "    return crc ^ 0xFFFFFFFF;\n"
        "}\n"
    )
    
    return c_code

if __name__ == "__main__":
    table = calculate_crc32_table()
    c_source = generate_c_file(table)
    print(c_source)